site:
  name: GitSite
  description: GitSite is a static web site generator for Git.
  keywords: gitsite, git, static web site, html
  theme: default
  contact:
    name: Michael Liao
    github: https://github.com/michaelliao/gitsite-cli
    twitter: https://twitter.com/liaoxuefeng

  search:
    # search by lunr or semantic:
    engine: lunr
    lunr-languages:
      - en
      - zh
    semantic-model: https://huggingface.co/Xenova/bge-small-zh/resolve/main/

  display:
    book-index-marker: true

  # you can add any items:
